### PR TITLE
Remove print leftover in the urlpatterns code.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Natim** [comment]
@chosak can you also take a look at the PR dropping support for Python3.6? Tests are not passing anymore with this arch on Githubactions apparently which prevent it to be merged.

**Comment by chosak** [comment]
@Natim yes, we'll take care of those - it seems like there are some linter failures unrelated to your PR as well.

**Comment by adamchainz** [comment]
Hehe I also removed the `print` in the unmerged Django 4.2 PR: https://github.com/cfpb/django-flags/pull/110#discussion_r1167094559

**Comment by Natim** [comment]
That would be awesome :pray: thanks :1st_place_medal:

**Comment by willbarton** [comment]
Combined and merged in https://github.com/cfpb/django-flags/commit/c95721e559bcc4fbfaa30e007e4a9ec2d7a17218 and https://github.com/cfpb/django-flags/commit/2667995ce649914a0bfecc0b18e1f42f9515b70a

**Comment by willbarton** [comment]
Thank you so much for the contribution, @Natim!!

**Pull request closed without merging**
